# Generated by Django 2.2.1 on 2019-05-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Humidity',
            fields=[
                ('humidity_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('humidity_value', models.DecimalField(decimal_places=4, max_digits=4)),
                ('date_created', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('temp_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('temp_value', models.DecimalField(decimal_places=4, max_digits=4)),
                ('date_created', models.DateField()),
            ],
        ),
    ]
