# Generated by Django 2.2.1 on 2019-05-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humidity',
            name='humidity_value',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='temp_value',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
